apiVersion: v1
kind: Service
metadata:
  name: rails-prometheus
  namespace: monitoring
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    name: rails-prometheus
  type: NodePort