apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    name: prometheus
  name: rails-prometheus
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      name: rails-prometheus
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        name: rails-prometheus
    spec:
      containers:
      - name: web
        image: johncena/rails-prometheus:latest
        args:
        - bin/start
        env:
        - name: RAILS_LOG_TO_STDOUT
          value: "true"
        - name: SECRET_KEY_BASE
          value: "320e0c0a905c6f641b3a2455b972ceb85b3ea9b49d77c8aaf7f816a2d8e55f3698cf9ca7d03c58637ada02b670a49163c23b0b8d923a537b78f88b2a75147ee9"
        - name: RACK_ENV
          value: 'production'
        - name: RAILS_ENV
          value: 'production'
        ports:
        - containerPort: 80
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 2500Mi
          requests:
            cpu: 100m
            memory: 100Mi
      restartPolicy: Always